version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: "${APP_NAME}_server"
    volumes:
      - ./nginx:/nginx/
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro #localtime
    depends_on:
      - php
    ports:
      - "${IP_SERVER}:80:80"
    command: nginx -g 'daemon off;'

  php:
    build: ./php
    image: php
    container_name: "${APP_NAME}_php"
    working_dir: /var/www/src
    volumes:
      - /etc/localtime:/etc/localtime:ro #localtime
      - ./cron:/etc/periodic
      - ./cron/crontab.txt:/var/spool/cron/crontabs/root
      - ./php-ci:/var/www/php-ci
      - ./nginx/conf/supervisord.conf:/etc/supervisor.d/job-queue.ini
      - ./src:/var/www/src/
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_HOST=${DOMAIN_DB}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${DOMAIN_REDIS}
      - REDIS_PORT=${REDIS_PORT}
      - MEMCACHE_HOST=${MEMCACHE_HOST}
      - MODE=DEV
    depends_on:
      - database
      - redis
      - memcached
    links:
      - database:${DOMAIN_DB}
      - redis:${IP_REDIS}
      - memcached:${DOMAIN_MEMCACHE}

  redis:
    image: redis:3.2.9-alpine
    container_name: "${APP_NAME}_redis"
    ports:
      - "${IP_REDIS}:6379:6379"

  memcached:
    image: 'memcached:1.5.20-alpine'
    container_name: ${APP_NAME}_memcached
    ports:
      - "${MEMCACHE_PORT}:${MEMCACHE_PORT_DOCKER}"
networks:
  default:
    external:
      name: "${APP_NAME}_network"
