version: "3.1"
services:
  webserver:
    image: nginx:alpine
    container_name: "${APP_NAME}_server"
    volumes:
      - ./nginx:/nginx/
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro #localtime
    depends_on:
      - php
    ports:
      - "${IP_SOURCE}:80:80"
    command: nginx -g 'daemon off;'

  php:
    build: ./php7.2
    image: php
    container_name: "${APP_NAME}_php"
    working_dir: /var/www/src
    volumes:
      - /etc/localtime:/etc/localtime:ro #localtime
      - ./cron:/etc/periodic
      - ./cron/crontab.txt:/var/spool/cron/crontabs/root
      - ./php-ci:/var/www/php-ci
      - ./nginx/conf/supervisord.conf:/etc/supervisor.d/job-queue.ini
      - ./src:/var/www/src/
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_DSN_VALUE=${DOMAIN_DB}
      - REDIS_HOST=${DOMAIN_REDIS}
      - REDIS_PORT=${REDIS_PORT}
      - MODE=DEV
    depends_on:
      - mysql
      - redis
    links:
      - mysql:${IP_DB}
      - redis:${IP_REDIS}
  mysql:
    image: mysql:5.5
    container_name: "${APP_NAME}_db"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - "${IP_DB}:3306:3306"
    command:
      - --innodb_use_native_aio=0
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci

  redis:
    image: redis:3.2.9-alpine
    container_name: "${APP_NAME}_redis"
    ports:
      - "${IP_REDIS}:6379:6379"

networks:
  default:
    external:
      name: "${APP_NAME}_network"
