version: "3.1"
services:
  database:
    image: mysql:5.5
    container_name: "${APP_NAME}_mysql"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${IP_MYSQL}:3306:3306"
    command:
      - --innodb_use_native_aio=0
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
networks:
  default:
    external:
      name: "${APP_NAME}_network"
