version: "3.1"
services:
  database:
    image: postgres:12.1-alpine
    container_name: "${APP_NAME}_postgres"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${IP_POSTGRES}:5432:5432"
networks:
  default:
    external:
      name: "${APP_NAME}_network"
